config/routes.rb
Rails.application.routes.draw do
  
  root "movies#index"
  
  resources :movies do
    resources :reviews
  end
  
  
  resources :users
  get "signup" => "users#new"
  
  resource :session, only: [:new, :create, :destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
    has_many :reviews, dependent: :destroy

    validates :title, :released_on, :duration, presence: true
    validates :description, presence: true, length: { minimum: 25 }
    validates :total_gross, presence: true, numericality: { greater_than_or_equal_to: 0 }
    validates :image_file_name, format: {
        with: /\w+\.(jpg|png)\z/i,
        message: "must be a JPG or PNG image"
    }
    RATINGS = %w(G PG PG-13 R NC-17)
    validates :rating, inclusion: { in: RATINGS }

    def self.released
        where("released_on < ?", Time.now).order("released_on desc")
    end

    def self.hits
        where("total_gross >= 300000000").order(total_gross: :desc)
    end
    
    def self.flops
        where("total_gross < 22500000").order(total_gross: :asc)
    end
    
    def self.recently_added
        order("created_at desc").limit(3)
    end

    def flop?
        total_gross.blank? || total_gross < 225000000
    end

    def average_stars
        reviews.average(:stars) || 0.0
    end

end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :movie

  validates :name, presence: true
  validates :comment, length: { minimum: 4 }
  STARS = [1, 2, 3, 4, 5]
  validates :stars, inclusion: { in: STARS, message: "must be between 1 and 5" }




end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password


  validates :name, presence: true
  validates :email, 
      presence: true,
      format: { with: /\S+@\S+/ },
      uniqueness: { case_sensitive: false }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

    def index
        @movies = Movie.released
    end

    def show
        @movie = Movie.find(params[:id])
    end

    def edit
        @movie = Movie.find(params[:id])
    end

    def update
        @movie = Movie.find(params[:id])
        if @movie.update(movie_params)
            redirect_to @movie, notice: "Movie successfully updated!"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def new
        @movie = Movie.new
    end

    def create
        @movie = Movie.new(movie_params)
        if @movie.save
            redirect_to @movie, notice: "Movie successfully created!"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def destroy
        @movie = Movie.find(params[:id])
        @movie.destroy
        redirect_to root_url, status: :see_other, alert: "Movie removed."
    end

private

    def movie_params
        params.require(:movie).
            permit(:title, :description, :rating, :released_on, :total_gross, :director, :duration, :image_file_name)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

    before_action :set_movie

    def index
        @reviews = @movie.reviews
    end

    def new
        @review = @movie.reviews.new
    end

    def create
        @review = @movie.reviews.new(review_params)
        if @review.save
            redirect_to movie_reviews_path(@movie), notice: "Thanks for your review!"
        else
            render :new, status: :unprocessable_entity
        end
    end



private

    def review_params
        params.require(:review).
            permit(:name, :stars, :comment)
    end

    def set_movie
        @movie = Movie.find(params[:movie_id])
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    
    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            session[:user_id] = user.id
            redirect_to user, notice: "Welcome back, #{user.name}!"
        else
            flash.now[:alert] = "Invalid email/password combination!"
            render :new, status: :unprocessable_entity
        end
    end
    
    def destroy
        session[:user_id] = nil
        redirect_to movies_url, status: :see_other, notice: "You're now signed out!"
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def show
        @user = User.find(params[:id])
    end

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to @user, notice: "Thanks for signing up!"
        else
            render :new, status: :unprocessable_entity
        end
    end

    def edit
        @user = User.find(params[:id])
    end

    def update
        @user = User.find(params[:id])
        if @user.update(user_params)
            redirect_to @user, notice: "Account successfully updated!"
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        session[:user_id] = nil
        redirect_to movies_url, status: :see_other,
            alert: "Account successfully deleted!"
    end


private
def user_params
    params.require(:user).
        permit(:name, :email, :password, :password_confirmation)
end




end

app/helpers/application_helper.rb
module ApplicationHelper

    def current_user
        User.find(session[:user_id]) if session[:user_id]
    end


end

app/helpers/movies_helper.rb
module MoviesHelper

    def total_gross(movie)
        if movie.flop?
            "Flop!"
        else 
            number_to_currency(movie.total_gross, precision:0)
        end
    end

    def year_of(movie)
        movie.released_on.strftime("%Y")
    end

end

app/helpers/reviews_helper.rb
module ReviewsHelper

    def average_stars(movie)
        if movie.average_stars.zero?
          content_tag(:strong, "No reviews")
        else
            pluralize(number_with_precision(movie.average_stars, precision: 1) , "star")        
        end
      end

end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
    <div class = "flash notice">
        <%= flash[:notice] %>
    </div>
<% end %>


<% if flash[:alert] %>
    <div class = "flash alert">
        <%= flash[:alert] %>
    </div>
<% end %>

app/views/layouts/_footer.html.erb
  <footer>
    <p>Copyright &copy <%= Time.now.year %></p>
  </footer>

app/views/layouts/_header.html.erb
  <header>
  <nav>
    <%= link_to image_tag("logo.png"), root_path %>

    <ul class="right">
    <% if current_user %>
      <li>
        <%= link_to current_user.name, current_user %>
      </li>
      <li>
        <%= link_to "Sign Out", session_path, data: { turbo_method: :delete }, class: "button" %>
      </li>
    <% else %>
      <li>
        <%= link_to "Sign In", new_session_path, class: "button" %>
      </li>
      <li>
        <%= link_to "Sign Up", signup_path, class: "button" %>
      </li>
    <% end %>
    </ul>
  </nav>
  </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flix</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

  <%= render "layouts/header" %>

  <div class="content">
    <%= render "layouts/flash" %>
    <%= yield %>
  </div>

  <%= render "layouts/footer" %>

  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |f| %>
    
    <%= render "shared/errors", object: movie %>

    <%= f.label :title %>
    <%= f.text_field :title, autofocus: true %>
    
    <%= f.label :description %>
    <%= f.text_area :description, rows:7 %>
    
    <%= f.label :rating %>
    <%= f.select :rating, Movie::RATINGS, prompt: "Pick one" %>
    
    <%= f.label :released_on %>
    <%= f.date_field :released_on %>
    
    <%= f.label :total_gross %>
    <%= f.number_field :total_gross %>

    <%= f.label :director %>
    <%= f.text_field :director %>

    <%= f.label :duration %>
    <%= f.text_field :duration %>

    <%= f.label :image_file_name %>
    <%= f.text_field :image_file_name %>

    <%= f.submit %>

<% end %>

app/views/movies/edit.html.erb
<h1>Editing <%= @movie.title %></h1>

<%= render "form", movie: @movie %>

app/views/movies/index.html.erb
    <% @movies.each do |movie| %>
        <section class="movie">
            <div class="image">
                <%= image_tag movie.image_file_name %>
            </div>
            <div class="summary">
                <h2><%= link_to movie.title, movie %></h2>
                <h3><%= total_gross(movie) %></h3>
                <p><%= truncate(movie.description, length:40, separator: ' ') %></p>
            </div>
        </section>
    <% end %>

<section class="admin">
    <%= link_to "Add New Movie", new_movie_path, class: "button" %>
</section>

app/views/movies/new.html.erb
<h1>Add a New Movie</h1>

<%= render "form", movie: @movie %>

app/views/movies/show.html.erb
<section class="movie-details">
    <div class="image">
        <%= image_tag @movie.image_file_name %>
    </div>
    <div class="details">
        <h1><%= @movie.title %></h1>
        <h2>
            <%= year_of(@movie) %> &bull; <%= @movie.rating %>
        </h2>
        <div class="reviews">
            <%= average_stars(@movie) %>
            <%= link_to pluralize(@movie.reviews.size, "review"), movie_reviews_path(@movie) %>
        </div>
        <p>
            <%= @movie.description %>
        </p>
        <table>
            <tr>
                <th>Director:</th>
                <td><%= @movie.director %></td>
            </tr>
            <tr>
                <th>Duration:</th>
                <td><%= @movie.duration %></td>
            </tr>
            <tr>
                <th>Total Gross:</th>
                <td><%= total_gross(@movie) %></td>
            </tr>
        </table>
        <%= link_to "Write Review", new_movie_review_path(@movie), class: "review" %>
    </div>
</section>

<section class="admin">
    <%= link_to "Edit", edit_movie_path(@movie), class: "button" %>
    <%= link_to "Delete", @movie, class: "button", 
        data: { turbo_method: :delete, turbo_confirm: "Really?!" } %>
</section>

app/views/reviews/index.html.erb
<h1>Reviews for <%= link_to @movie.title, @movie %></h1>
<ul class="reviews">
    <% @reviews.each do |review| %>
    <li>
      <%= pluralize(review.stars, 'star') %>
      <p>
        <%= review.name %>
        <span class="date">
          <%= time_ago_in_words(review.created_at) %> ago
        </span>
      </p>
      <p>
        <%= review.comment %>
      </p>
    </li>
  <% end %>
</ul>

app/views/reviews/new.html.erb
<h1>New Review for <%= link_to @movie.title, @movie %></h1>

<%= form_with(model: [@movie, @review]) do |f| %>
    <%= render "shared/errors", object: @review %>

    <%= f.label :name %>
    <%= f.text_field :name, autofocus: true %>
    
    <%= f.label :stars %>
    <%= f.select :stars, Review::STARS, prompt: "Pick One" %>

    <%= f.label :comment %>
    <%= f.text_area :comment, placeholder: "What did you think?" %>

    <%= f.submit "Post Review" %>

<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <section class="errors">
    <h2>
      Oops! Your form could not be saved.
    </h2>
    <h3>
      Please correct the following
      <%= pluralize(object.errors.size, "error") %>:
    </h3>
    <ul>
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </section>
<% end %>

app/views/shared/_stars.html.erb
<div class="star-rating">
  <div class="back-stars">
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <span>★</span>
    <div class="front-stars" style="width: <%= percent %>%">
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
      <span>★</span>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
<%= form_with(model: user) do |f| %>
  <%= render "shared/errors", object: user %>

  <%= f.label :name %>
  <%= f.text_field :name, autofocus: true %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %>

  <% if user.new_record? %>
    <%= f.submit "Create Account" %>
<% else %>
    <%= f.submit "Update Account" %>
<% end %>

<% end %>

app/views/users/edit.html.erb
<h1>Edit Account</h1>

<%= render "form", user: @user %>

app/views/users/index.html.erb
<h1><%= pluralize(@users.size, "User") %></h1>
<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= link_to user.name, user %>
      created
      <%= time_ago_in_words(user.created_at) %> ago
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= render "form", user: @user %>

app/views/users/show.html.erb
<section class="user">
  <h1><%= @user.name %></h1>
  <h2><%= mail_to(@user.email) %></h2>

  <div class="actions">
    <%= link_to "Edit Account", edit_user_path(@user), class: "button edit" %>
    <%= link_to "Delete Account", @user, class: "button delete",
        data: { turbo_method: :delete, turbo_confirm: "Permanently delete your account!?" } %>

  </div>
</section>